# BUILD STAGE
FROM node:18 AS builder

# Set working directory inside container
WORKDIR /app

# Copy the package.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy all other source files to the container
COPY . .

# Build the app for production
RUN npm run build

#######################

# PRODUCTION STAGE (NGINX)
FROM nginx:latest

# Copy the built frontend from the builder stage into NGINX's html directory
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80 for the NGINX server
EXPOSE 80

# Run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]
