# frontend/Dockerfile

# Build stage
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Just an artifact, not serving via container anymore

# tjMeI0AvvPwowOG4IvYM1KWwuBXztCew0j7yDwkI