
# FROM node:18-alpine

# WORKDIR /app

# COPY /package*.json /

# RUN npm install

# COPY . .

# RUN npm run build

# EXPOSE 5173

# RUN npm install serve

# CMD [ "serve" ,"-s","build","-l","5173" ]

############################# MULTI STAGED DOCKER ####################


# BUILD STAGE 
FROM node:18 AS builder

#SET WORKINGDIR
WORKDIR /app

#CPY package*json
COPY /package*.json .

#INSTALL DEPENDICIES
RUN npm install --production

#COPY ENTIRE FILE 
COPY . .

#BUILD FOR PRODUCTION
RUN npm run build

#######################

FROM nginx:latest

COPY --from=builder /app/dist usr/share/nginx/html

EXPOSE 80

CMD [ "nginx" , "-g" , "daemon off;" ]
