# Build Stage (optional, only for installing dependencies)
FROM node:18 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Production Stage
FROM node:18-slim AS runner
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm install --only=prod
COPY --from=builder /app ./
EXPOSE 4000
CMD ["node", "server.js"]


