---
- name: Provision EC2 and deploy backend container
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Nginx (optional - only if you want reverse proxy)
      apt:
        name: nginx
        state: present

  