# BUILD STAGE

FROM node:18 AS builder

WORKDIR /app

COPY ./package*.json .

RUN npm install --production

COPY . .

RUN npm run build

#####################################

# SERVER STAGE

FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx" ,"-g" , "daemon off;" ]