name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm run lint
        npm test

    - name: Install and Test Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run lint
        npm test

  docker-build-push:
    needs: build-test-lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build & Push Backend Docker Image
      working-directory: ./backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest

    - name: Build & Push Frontend Docker Image
      working-directory: ./frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
